### ISSUE TITLE
audit-argument-checks 

### ISSUE THREAD

**Issue by NitroBAY** [Lepozepo/cloudinary#100]
Your package has audit-argument-checks as a dependency so I have this problem  Did not check() all arguments during call to 'Worksheets.insert' on other methods than cloudinary one.
By the way I do check the data but maybe as I use a function instead of directly checking audit-argument-checks throws an error.

**Comment by Lepozepo** [comment]
Hey! Yeah, I really need to give this package some love. Isn't `audit-argument-checks` a weak dependency? Let me see

**Comment by Lepozepo** [comment]
Lol https://github.com/Lepozepo/cloudinary/blob/master/package.js#L19, ok, I'll patch this as soon as I can

**Comment by NitroBAY** [comment]
Great thanks. I tested it by downloading package and removing "weak dependency" and it solved my problem.

**Comment by Lepozepo** [comment]
This should be fixed with da9ce63d477922128386768d7383a94f0b46ef1c in the latest release
