### ISSUE TITLE
Documentation on how to sign packages.

### ISSUE THREAD

**Issue by NicholasEli** [Lepozepo/cloudinary#104]
I am trying to get this package to work. How ever I think my uploads neee to be signed. 

Is there any docs to follow for this?

**Comment by NicholasEli** [comment]
Never mind, I figured out my issue. Was using incorrect cloud name.  I am greateful you made this package. I will drop a donation later this week. 

Thanks!

**Comment by Lepozepo** [comment]
Awesome! Glad you were able to solve it. Sorry I didn't respond sooner, I wasn't sure what could've been wrong.
