### ISSUE TITLE
Remove templating/Blaze dependency

### ISSUE THREAD

**Issue by lmachens** [Lepozepo/cloudinary#113]
It would be great to remove the templating/Blaze dependency.
This would be a breaking change, but more and more projects getting rid of Blaze.

[Necessary changes](https://github.com/lmachens/cloudinary/pull/2/files)

Maybe another solution is possible where the blaze templates are optional?

**Comment by Lepozepo** [comment]
Definitely, I haven't had a lot of time to put into my open source projects this year but I will be creating an NPM version of this package just like I did for my S3 package as soon as I can.

**Comment by lmachens** [comment]
Ok great! In the meantime I use my fork without the dependencies, JS examples and extended Cloudinary class on the client side.
[Fork](https://github.com/lmachens/cloudinary)
