### ISSUE TITLE
Upload to specific folder?

### ISSUE THREAD

**Issue by fabyeah** [Lepozepo/cloudinary#22]
Thank you @Lepozepo for making this package.

Is it possible to upload to a certain folder?

I tried `{{#c_upload_stream folder=folder callback="save_url"}}` without success.

**Comment by Lepozepo** [comment]
Sorry, that's not supported right now but I'll look into it when I get a chance.

**Comment by Lepozepo** [comment]
You can now upload to a specific folder using the `Cloudinary.upload(files,ops,callback)` function. `ops` will take in the `folder` parameter. I'll elaborate in the docs next time I get a chance.

**Comment by fabyeah** [comment]
Thanks for the update! Uploading to a folder works, but I can't seem to read from it.
How to I pass the folder to the url helper?
`<img src="{{c.url public_id folder='test' format=format width=600 height=200 crop='limit'}}"` doesn't seem to work.

**Comment by fabyeah** [comment]
Ok, so the folder will be part of the public_id. So there is no need to pass 'folder' when retrieving images.
