### ISSUE TITLE
Security: checking all arguments

### ISSUE THREAD

**Issue by workflow** [Lepozepo/cloudinary#24]
Hi @Lepozepo,

thx for this package!

With `audit-argument-checks` enabled, your package is throwing the following:

```
Exception while invoking method 'cloudinary_upload' Error: Did not check() all arguments during call to 'cloudinary_upload'
```

Could you include a check() in all methods?

**Comment by Lepozepo** [comment]
Definitely! I'll patch it this weekend hopefully.

**Comment by Lepozepo** [comment]
I've added checks for the new version but there are a lot of breaking changes so be sure to read the docs before updating.

**Comment by workflow** [comment]
Awesome, thx!
