### ISSUE TITLE
no such package

### ISSUE THREAD

**Issue by dansurfs** [Lepozepo/cloudinary#27]
Hello, 
Thank you for making this.
I tried using ' meteor add cloudinary' and got the result in the picture.
What's the best way to go about getting this package to install? Thanks.
![no such package](https://cloud.githubusercontent.com/assets/8673591/8556397/aa63479e-24ab-11e5-8475-bd12a5fb9f8c.png)

**Comment by Lepozepo** [comment]
Lol, you forgot to add my username. So the package install command would be `meteor add lepozepo:cloudinary`
