### ISSUE TITLE
c_upload_stream seems to work with only small files

### ISSUE THREAD

**Issue by arathipanya** [Lepozepo/cloudinary#29]
Hi,
I am using #c_upload_stream to upload some pictures on Cloudinary, with also  _cloudinary.after.update

In local everything works fine but once in production, when I upload a file > 900ko nothing happens...

Here is my code
<pre>
//In template html imageForm
{{#c_upload_stream callback="save_url"}}
</pre>
    <input type="file" accept="image/*;capture=camera">

    <div id="p-image-loading" style="display:none;">
	  Uploading...
    </div>
<pre>
{{/c_upload_stream}}
</pre>

<pre>
//In front js
Template.imageForm.events({
    "change input[type='file']": function(e) {
        var files = $("input")[0].files;

        C.upload_stream(files, function(res) {
            console.log("RES", res);
        });
    }
})

_cloudinary.after.update(function(user,file){
    if(file.percent_uploaded === 100 && !file.uploading){
        $('#p-image-loading').hide();
        Session.set("image-uploading", false);
        console.log("getting image...");
        var _img = $.cloudinary.image(file.public_id, {
        	transformation: [{width: 150, height: 170, crop: "fill"}]
        });
        $('#p-image-upload').html(_img[0].outerHTML+'<input type="hidden" name="image" accept="image/*;capture=camera" value="'+file.public_id+'" />');
    } else {
        console.log("loading....");
    	$('#p-image-upload').html('');
    	$('#p-image-loading').show();
    	Session.set("image-uploading", true);
    }
})
</pre>

I get neither some errors nor console logs...

I hope it is clear :s !
Thanks,

**Comment by Lepozepo** [comment]
Upgrade to the latest version, we are not using streams anymore.



Marcelo Reyna

**Comment by arathipanya** [comment]
Oh, good to know :)
My bad, thank you

**Comment by Lepozepo** [comment]
No problem :D



Marcelo Reyna

**Comment by arathipanya** [comment]
It works perfectly.
Here is my version : 
<pre>
Template.imageForm.events({
    "change input[type='file']": function(e) {
        var files = e.target.files;

        //show an uploading message...
        Session.set("image-uploading", true);

        Cloudinary.upload(files, {}, function(err, res) {
            //hide uploading message...
            Session.set("image-uploading", false);

            var _img = $.cloudinary.image(res.public_id, {
                transformation: [{width: 150, height: 170, crop: "fill"}]
            });
            //append uploaded image _img
        });
    }
})
</pre>
