### ISSUE TITLE
Showing file upload progress in v4.0.0

### ISSUE THREAD

**Issue by fabyeah** [Lepozepo/cloudinary#30]
Is it possible to display file upload progress in the new version?

**Comment by Lepozepo** [comment]
It is, just pick up the amount loaded and divide it by the total from the data in the request object that the collection produces. Have a look at the basic example.



Marcelo Reyna

**Comment by Lepozepo** [comment]
Have a look at https://github.com/Lepozepo/cloudinary/issues/60
