### ISSUE TITLE
Did not check() all arguments

### ISSUE THREAD

**Issue by torayeff** [Lepozepo/cloudinary#39]
How can be this fixed:
```I20150818-09:34:57.766(5)? Exception while invoking method 'c.sign' Error: Did not check() all arguments during call to 'c.sign'```

**Comment by Lepozepo** [comment]
That's strange, I do have a very low-level `check` on the signing method. What security packages do you have installed?

**Comment by torayeff** [comment]
nothing except audit argument check

**Comment by Lepozepo** [comment]
I'll double check when I get home



Marcelo Reyna

**Comment by Lepozepo** [comment]
Lol, I updated my s3 package instead of this one >_<, it should be a quick fix though

**Comment by Lepozepo** [comment]
This should be good now
