### ISSUE TITLE
Error when uploading (server side)

### ISSUE THREAD

**Issue by arnoldgamboa** [Lepozepo/cloudinary#44]
Hi,

I'm getting this error from the server side while uploading the image:

`Exception while invoking method 'c.sign' ReferenceError: check is not defined`

Any idea?

**Comment by Lepozepo** [comment]
Did you update to 1.2? Maybe I need to check for the existence of check before running it, I thought it was part of the core. Look for meteor's check package and add it if you need it to work ASAP, if not I'll patch it up tonight if I get a chance.

**Comment by arnoldgamboa** [comment]
Yes, it's 1.2. So, this might be due to the upgrade?

**Comment by arnoldgamboa** [comment]
I am able to make it work by adding "check" and "random" packages. Thanks.

**Comment by Lepozepo** [comment]
Excellent, that will affect all your meteor methods though, make sure to use check in every method you have now. This is good for security anyway if you're planning on taking your app to production someday.

**Comment by arnoldgamboa** [comment]
Oh, I never thought it would. Hmm.. might not be a good way to do it since
my codebase is huge already. I'll just wait for your update, then?

**Comment by Lepozepo** [comment]
Sounds good



Marcelo Reyna

**Comment by Lepozepo** [comment]
The code is checking for check now ^_^
