### ISSUE TITLE
Problem with uploading to server

### ISSUE THREAD

**Issue by arnoldgamboa** [Lepozepo/cloudinary#46]
I have 4.0.0 working locally (can't seem to upgrade to 4.0.1, I'm not sure why). But when I'm uploading to live server (through mup), it breaks it. Attached is the screenshot. Any idea why?

Thanks!

![speakactive](https://cloud.githubusercontent.com/assets/587603/10115842/dcb39616-644a-11e5-8a39-5e4f5dddfcbc.jpg)

**Comment by arnoldgamboa** [comment]
If it would help, here's where the error is coming from. Take note that everything seems to be working fine in my local build.

![speakactive_and_slack](https://cloud.githubusercontent.com/assets/587603/10115873/6894073c-644c-11e5-90e2-ea217820ab93.jpg)

**Comment by Lepozepo** [comment]
Is your production server behind SSL?



Marcelo Reyna

**Comment by arnoldgamboa** [comment]
It's not. 

Sent from iPhone




On Sat, Sep 26, 2015 at 12:08 PM -0700, "Marcelo Reyna" <notifications@github.com> wrote:










Is your production server behind SSL?







Marcelo Reyna



On Fri, Sep 25, 2015 at 11:45 PM, Arnold Gamboa <notifications@github.com>

wrote:

**Comment by arnoldgamboa** [comment]
... and previous version of your package (before 4.0) works on the server, too (if that helps).

Thanks!

-Arnold

**Comment by Lepozepo** [comment]
What does your code look like? The most current version of this package only supports client side uploads and I think the commands are a bit different.



Marcelo Reyna

**Comment by arnoldgamboa** [comment]
Solved it.

It's how c.url is treated. What's what helped: http://www.heapoverflow.me/question-display-a-profile-photo-with-meteor-32187497

(I wonder though why it worked locally and not on the server)

**Comment by Lepozepo** [comment]
Hmm, that looks like the helper wasn't being used right. c.url expects a public ID not a url. Still, it is surprising that it was working. It sounds like it might be an issue with cloudinary's javascript plugin. @TalLevAmi what do you think?

**Comment by TalLevAmi** [comment]
@Lepozepo Not sure I fully understand the issue, but cloudinary_url is not meant to be called with null/undefined. If that's an issue with the Meteor integration, we can add a shortcut that returns null/undefined in this case. Will that help?

**Comment by Lepozepo** [comment]
@TalLevAmi I guess it would be good for both cloudinaryJS and my helper to return something instead of breaking the rest of the code when public_id is falsy. I'm trying to understand why it would fail for @arnoldgamboa in production but not locally. Maybe something inside his loop is returning false and messing things up in production. Could you check @arnoldgamboa ?

**Comment by TalLevAmi** [comment]
See https://github.com/cloudinary/cloudinary_js/commit/aacb2a504b789d92176ac4ad64ec7c5f3f06b993

**Comment by Lepozepo** [comment]
Sweet! Thanks @TalLevAmi

**Comment by Lepozepo** [comment]
Fixed with cf44f2262af6e4532989331780a3ee98a2173a09 I think, @arnoldgamboa please test further to see if it's anything else ^_^.

**Comment by arnoldgamboa** [comment]
Thank you guys for the help. 

Sent from iPhone




On Mon, Sep 28, 2015 at 11:10 PM -0700, "Marcelo Reyna" <notifications@github.com> wrote:












Fixed with cf44f22 I think, @arnoldgamboa please test further to see if it's anything else ^_^.
