### ISSUE TITLE
Video uploads

### ISSUE THREAD

**Issue by arnoldgamboa** [Lepozepo/cloudinary#48]
I noticed that Cloudinary supports video uploads. Is that something that your package plans to support in the future?

**Comment by Lepozepo** [comment]
Definitely!

**Comment by arnoldgamboa** [comment]
... or is that something available now? Like maybe a method that's been there but not being used?

**Comment by Lepozepo** [comment]
Maybe, I'm not sure if the signature will work though.



Marcelo Reyna

**Comment by patrickbolle** [comment]
Anyone ever get video uploads working?
