### ISSUE TITLE
Exception while invoking method 'c.sign' ReferenceError: check is not defined

### ISSUE THREAD

**Issue by andregoldstein** [Lepozepo/cloudinary#49]
Has anyone seen this error? Have just created a fresh install and followed instructions but the Cloudinary call is not happening and am getting the above error?

Thanks.

**Comment by andregoldstein** [comment]
Update: I had figured the `check` package was part of core but maybe not, have just installed it and now getting another error:

`Exception in delivering result of invoking 'c.sign': ReferenceError: Random is not defined`

**Comment by andregoldstein** [comment]
Update 2:

Turns out `random` is another non-core package, added that and all OK! Maybe consider adding it as a dependency?

**Comment by meandkareem** [comment]
just do 'meteor add check'

**Comment by andregoldstein** [comment]
Thanks @meandkareem I should have updated the comment to say this worked for me when I tried it. Have now stumbled onto issue #50

**Comment by fabyeah** [comment]
@Lepozepo Just ran into this today. As of Meteor 1.2 check and random are removable, so the package itself should add a dependency to those, instead of having to add them to the entire meteor app!?
