### ISSUE TITLE
Transformations have no effect

### ISSUE THREAD

**Issue by andregoldstein** [Lepozepo/cloudinary#50]
Hi again, I'm having issues where whatever transformations I try to apply the image is just returned as a normal full image. Am using the example given:

```
<img src="{{c.url public_id width=250 height=250 crop="fill"}}">
```

**Comment by rfines** [comment]
I am not 100% sure but I think you need the format as well. 

    <img src="{{c.url public_id width=250 height=250 crop="fill" format=format}}">

Here is how I have been able to get the transformations to work:

    <img src="{{c.url publicId format=format gravity='faces' mode='thumb' crop='thumb' height=80 width=80}}" alt="profile image" class="image profile-image" />

with publicId and format being helpers in my associated .js file.

**Comment by andregoldstein** [comment]
Thanks @rfines . As it turned out I was doing something stupid. I wasn't referencing my individual `image` template inside my `images` template, I was still using a static img. Apologies.
