### ISSUE TITLE
v4.0.4 is not on atmosphere

### ISSUE THREAD

**Issue by chmac** [Lepozepo/cloudinary#55]
Atmosphere [shows](https://atmospherejs.com/lepozepo/cloudinary) 4.0.3 but the `package.js` file [here](https://github.com/Lepozepo/cloudinary/blob/master/package.js) shows 4.0.4. Maybe you need to run `meteor publish` in the package directory to push the latest version?

**Comment by chmac** [comment]
Oh, and by the way, for anyone else who finds this issue, we solved it temporarily by cloning this repository directly into the meteor `packages/` directory like `git clone git@github.com:Lepozepo/cloudinary.git`.

**Comment by Lepozepo** [comment]
The latest version is now in atmosphere ^_^, something is up with my notifications that I'm not receiving any of these issues, lol.
