### ISSUE TITLE
No Cloudinary.delete on the server?

### ISSUE THREAD

**Issue by ciwolsey** [Lepozepo/cloudinary#57]
I have an app where posts (which have images) expire after 21 days. I have a cron job that runs every hour that removes all posts older than 21 days. I also need to remove images from cloudinary but it seems Cloudinary.delete isn't defined on the server. Is this possible?

**Comment by danielparas** [comment]
@ciwolsey was looking for the same thing. Has already been answered here https://github.com/Lepozepo/cloudinary/issues/38
