### ISSUE TITLE
Abort upload

### ISSUE THREAD

**Issue by CyrilSabbagh** [Lepozepo/cloudinary#58]
Hi, 
I am using ng-file-upload to upload images and I want to hook a cancel button that will abort the current upload process. I can't find a way to get the XHR request object so I can abort it.
Do you have any tips on how I can do this?
Thanks!

**Comment by Lepozepo** [comment]
Hi! There is currently no way to do it, you would have to patch the package to expose the xhr object from `functions.coffee`. If I get a chance some time today to patch it up I'll push an update but feel free to make a pull request ^_^

**Comment by CyrilSabbagh** [comment]
Done ! :)

**Comment by Lepozepo** [comment]
Sweet, it's in, thanks ^_^
