### ISSUE TITLE
Cordova Android Bug with Meteor 1.2+, broken file upload

### ISSUE THREAD

**Issue by fabyeah** [Lepozepo/cloudinary#64]
Just a heads up: It is now neccessary to define ```App.accessRule("blob:*");``` for file upload to work on android devices.
A note in the documentation would be nice, like CollectionFS did: https://github.com/CollectionFS/Meteor-CollectionFS/blob/master/README.md#cordova-android-bug-with-meteor-12

Might save people a lot of time. I certainly wish I found that earlier. ;)

**Comment by Lepozepo** [comment]
Added to README ^_^
