### ISSUE TITLE
Page refuses to render image

### ISSUE THREAD

**Issue by emaddoma** [Lepozepo/cloudinary#75]
```
<img src="{{c.url cloudinary.public_id}}">
```

throws this error: "Refused to load the image 'http://res.cloudinary.com/hud9ala09/image/upload/aslngmemx51tli3uof1c' because it violates the following Content Security Policy directive: "img-src data: 'self' localhost:* http://fonts.googleapis.com https://fonts.googleapis.com http://fonts.gstatic.com https://fonts.gstatic.com http://graph.facebook.com https://graph.facebook.com http://fbcdn-profile-a.akamaihd.net https://fbcdn-profile-a.akamaihd.net http://secure.gravatar.com https://secure.gravatar.com http://i0.wp.com https://i0.wp.com http://*.facebook.com https://*.facebook.com http://*.fbcdn.net https://*.fbcdn.net http://connect.facebook.net https://connect.facebook.net http://*.googleusercontent.com https://*.googleusercontent.com http://*.stripe.com https://*.stripe.com http://enginex.kadira.io https://enginex.kadira.io http://www.google-analytics.com https://www.google-analytics.com http://*.doubleclick.net https://*.doubleclick.net http://cdn.mxpnl.com https://cdn.mxpnl.com http://cdn.segment.com https://cdn.segment.com http://www.paypal.com https://www.paypal.com http://www.paypalobjects.com https://www.sandbox.paypal.com https://www.paypalobjects.com https://tracking.qa.paypal.com"."

**Comment by Lepozepo** [comment]
Looks like you need to allow content from Cloudinary in your security policy. I don't remember exactly how to do that but I'm sure you can find out how quickly on their docs.

Marcelo Reyna
702 769 0639

**Comment by emaddoma** [comment]
Thanks.  I added BrowserPolicy.content.allowImageOrigin("res.cloudinary.com"); to policy.js and it's working now.
