### ISSUE TITLE
Ionic/Angular on Meteor?

### ISSUE THREAD

**Issue by arnoldgamboa** [Lepozepo/cloudinary#78]
Hi,

Is there a chance this works on new member of the Meteor family, AngularJS? I'm particularly planning on using it with IonicFramework on Meteor. Or has this been converted to AngularJS somewhere?

**Comment by Lepozepo** [comment]
The helpers will not work since they are programmed specifically for Blaze, you can definitely tap into their underlying functions to make work with something like angular. I'm not sure if support for angular is something I have in the scope of this project, I'm more likely to pick React.
