### ISSUE TITLE
Exception in delivering result of invoking 'c.sign': Error: [Internal server error [500]]

### ISSUE THREAD

**Issue by jessylachapelle** [Lepozepo/cloudinary#88]
## Version & platform

- Ubuntu Gnome 14.04
- Chromium 48.0.2564.116
- node v5.11.1
- npm 3.8.6
- check@1.1.0

## Expected behaviour

On using function:
`Cloudinary.upload(files, { folder }, (err, res) => { callback(err, res); });`

- Files should be uploaded to Cloudinary
- Return the information about the upload.

## Actual behaviour

- Files not uploaded
- Exception is thrown : Exception while invoking method 'c.sign'
![screenshot from 2016-06-29 11 11 33](https://cloud.githubusercontent.com/assets/7608273/16457663/432c42f2-3dea-11e6-9f85-d96947c3a132.png)

## Solution leads

The problem seems to be here :
https://github.com/Lepozepo/cloudinary/blob/54f373934c9457c1b2084cda16999766a7adeb51/server/signature.coffee#L4-L18

- The `check ops, Match.Maybe(Object)` seems to be what is causing the issue.

**Comment by Lepozepo** [comment]
Hmm, I'll review this coming weekend but PR's are appreciated ^_^ what version of Meteor are you on?

**Comment by jessylachapelle** [comment]
I can see to do a PR next week, the issue is with the check package. My app is stuck at an older version because of dependencies, in that version Match.Maybe() does not exist yet. A quick fix was to add the code for Match.Maybe from the source directly in my project.

Meteor version is 1.2.1
