### ISSUE TITLE
upload a file created using a blob

### ISSUE THREAD

**Issue by fabianrios** [Lepozepo/cloudinary#89]
trying to do this but not working I don't even get an error.
`var myFile = new File([blob], "new_file.png", {type: "image/png"});
        Cloudinary.upload(myFile,{},function(err, res){
          if (!err == null){
           console.log('upload error: ' + err);
          }else{
           console.log('upload result: ' + JSON.stringify(res));
          }
        });`

**Comment by Lepozepo** [comment]
Should be fixed in 1815b329f21ca2cbb4f3f5f94e0d9be31f00d93b
