### ISSUE TITLE
Cloudinary.upload on the server for security reasons?

### ISSUE THREAD

**Issue by fabyeah** [Lepozepo/cloudinary#93]
I'm very happy with this package! Just two things I don't know how to accomplish now:

1. Set the allowed image formats on server side via allowed_formats
2. Use addons like the Metascan Anti-malware Protection Add-on (http://cloudinary.com/documentation/metascan_anti_malware_protection_addon) to prevent users from uploading malicious files. Use of the addon should also be enforced server side.

Is this possible? Maybe it is an option to have both ways of uploading available and the direct client upload as default?

**Comment by fabyeah** [comment]
I figured out how to do both by defining a default upload preset in the cloudinary upload settings.

http://cloudinary.com/blog/centralized_control_for_image_upload_image_size_format_thumbnail_generation_tagging_and_more

**Comment by Lepozepo** [comment]
Sweet! Sorry I didn't answer sooner, I honestly hadn't used that feature before ^_^. Thanks for posting an answer :D
