### ISSUE TITLE
does this work with Meteor v1.4.x?

### ISSUE THREAD

**Issue by szimmers** [Lepozepo/cloudinary#98]
i'm testing out our app w/ the upgraded version, from v1.3.5.1. The symptom is that the files don't upload to cloudinary.

when i debug the client, _upload_file is never called. so we never make it as far as the server "c.sign" method.

i ran a meteor update on this package and the indication was i already had the latest compatible version.

has anyone gotten this working? is there something i forgot to do?

**Comment by Lepozepo** [comment]
Hmm, it should work. Have you looked at the sample project? If that one fails then I'll have a look as soon as I can. pR's always welcome!

**Comment by ABAD-i** [comment]
On METEOR@1.4.1 working fine , but it not working on METEOR@1.4.1.1 ,
 i got this error Cannot read property 'config' of undefined :( ?

**Comment by goooseman** [comment]
@Lepozepo made a PR with a fix

**Comment by Lepozepo** [comment]
@goooseman Thank you for the PR! The check for files, blobs, filelists, and arrays was very stupidly built. I just patched it in the latest release. There shouldn't be any more problems ^_^
